//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP_02_EL_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersProduct
    {
        public int Id { get; set; }
        public int IDProduct { get; set; }
        public int IDPartner { get; set; }
        public int ProductCount { get; set; }
        public System.DateTime DateOfRealization { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
