//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP_02_EL_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnersProduct = new HashSet<PartnersProduct>();
        }
    
        public int ID { get; set; }
        public int IDType { get; set; }
        public string Name { get; set; }
        public string DirectorsLastName { get; set; }
        public string DirectorsFirstName { get; set; }
        public string DirectorsMidleName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
    
        public virtual PartnersType PartnersType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnersProduct> PartnersProduct { get; set; }
    }
}
